apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-booking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-booking-app
  template:
    metadata:
      labels:
        app: device-booking-app
    spec:
      containers:
        - name: app
          image: YOUR_DOCKERHUB/device-booking-app:latest
          ports:
            - containerPort: 8080